// Unified anatomy catalog, generated by scripts/export_systems.py (one JSON per system).
// `id` is the single source of truth: it equals the GLB node name AND links to depth/region.
// All 9 systems wired (skeletal, muscular, joints, cardiovascular, nervous, visceral,
// lymphoid, regions, insertions).
import skeletalRaw from './skeletal.catalog.json';
import muscularRaw from './muscular.catalog.json';
import jointsRaw from './joints.catalog.json';
import cardiovascularRaw from './cardiovascular.catalog.json';
import nervousRaw from './nervous.catalog.json';
import visceralRaw from './visceral.catalog.json';
import lymphoidRaw from './lymphoid.catalog.json';
import regionsRaw from './regions.catalog.json';
import insertionsRaw from './insertions.catalog.json';

export type SystemId =
  | 'skeletal' | 'muscular' | 'joints' | 'cardiovascular'
  | 'nervous' | 'visceral' | 'lymphoid' | 'regions' | 'insertions';
export type Depth = 'superficial' | 'deep' | 'unknown';

export interface Structure {
  id: string;
  nameEn: string;
  nameLatin: string;
  nameFa: string;
  descriptionEn: string;
  descriptionFa: string;
  system: SystemId;
  region: string;
  depth: Depth;
  depthOrder: number;
  depthSource: string | null;
  aliases: string[];
}

export interface SystemDef {
  id: SystemId;
  label: string;
  model: string;
  color: string;
  defaultOn: boolean;
}

// Order = how they appear in the Layers panel. Only skeleton is on by default.
export const SYSTEMS: SystemDef[] = [
  { id: 'regions', label: 'Body surface', model: '/models/regions.glb', color: '#d8b89a', defaultOn: false },
  { id: 'muscular', label: 'Muscles', model: '/models/muscular.glb', color: '#b5615a', defaultOn: false },
  { id: 'nervous', label: 'Nerves & brain', model: '/models/nervous.glb', color: '#e3c64d', defaultOn: false },
  { id: 'cardiovascular', label: 'Vessels & heart', model: '/models/cardiovascular.glb', color: '#c0392b', defaultOn: false },
  { id: 'visceral', label: 'Organs', model: '/models/visceral.glb', color: '#c98f6a', defaultOn: false },
  { id: 'lymphoid', label: 'Lymphoid', model: '/models/lymphoid.glb', color: '#6fae8f', defaultOn: false },
  { id: 'joints', label: 'Joints', model: '/models/joints.glb', color: '#7fb0c0', defaultOn: false },
  { id: 'insertions', label: 'Muscle insertions', model: '/models/insertions.glb', color: '#9a8f7a', defaultOn: false },
  { id: 'skeletal', label: 'Skeleton', model: '/models/skeletal.glb', color: '#e3ddcd', defaultOn: true },
];

export const SYSTEM_BY_ID = new Map(SYSTEMS.map((s) => [s.id, s]));

// Draco decoder is self-hosted under public/draco/ — no runtime CDN dependency.
export const DRACO_DECODER_PATH = '/draco/';

export const structures: Structure[] = [
  ...(skeletalRaw as Structure[]),
  ...(muscularRaw as Structure[]),
  ...(jointsRaw as Structure[]),
  ...(cardiovascularRaw as Structure[]),
  ...(nervousRaw as Structure[]),
  ...(visceralRaw as Structure[]),
  ...(lymphoidRaw as Structure[]),
  ...(regionsRaw as Structure[]),
  ...(insertionsRaw as Structure[]),
];

export const byId = new Map(structures.map((s) => [s.id, s]));
export const validIds = new Set(structures.map((s) => s.id));

/** Normalize a GLB node name (strip Blender .001 suffixes, lowercase). */
export function normalizeName(raw: string): string {
  return raw.toLowerCase().replace(/\.\d+$/, '').trim();
}

// alias → id, so any leftover part/landmark node still resolves to its structure.
const aliasIndex = new Map<string, string>();
for (const s of structures) {
  for (const a of s.aliases) aliasIndex.set(normalizeName(a), s.id);
}

/** Resolve a GLB node name to a structure id (direct id, then alias), or null. */
export function resolveStructureId(nodeName: string): string | null {
  const n = normalizeName(nodeName);
  if (validIds.has(n)) return n;
  return aliasIndex.get(n) ?? null;
}

export function isDepthVisible(depth: Depth, sub: { superficial: boolean; deep: boolean }): boolean {
  if (depth === 'superficial') return sub.superficial;
  if (depth === 'deep') return sub.deep;
  return true; // unknown is ALWAYS visible — never auto-hidden
}
